trees:
    default:
        adapter: ezpublish
        root_locations: [2, 43, 5]
        categories:
            types: [frontpage, folder]
    tags:
        adapter: eztags
        root_locations: [0]
        default_columns: [name]
        template: 'NetgenContentBrowserBundle:eztags:item.html.twig'

adapters:
    ezpublish: ~
