parameters:
    netgen_content_browser.controller.api.tree.class: Netgen\Bundle\ContentBrowserBundle\Controller\API\TreeController

    netgen_content_browser.ezpublish.thumbnail_loader.variation.class: Netgen\Bundle\ContentBrowserBundle\Adapter\EzPublish\ThumbnailLoader\VariationThumbnailLoader
    netgen_content_browser.ezpublish.item_builder.class: Netgen\Bundle\ContentBrowserBundle\Adapter\EzPublish\ItemBuilder
    netgen_content_browser.ezpublish.adapter.class: Netgen\Bundle\ContentBrowserBundle\Adapter\EzPublish\Adapter

    netgen_content_browser.eztags.item_builder.class: Netgen\Bundle\ContentBrowserBundle\Adapter\EzTags\ItemBuilder
    netgen_content_browser.eztags.adapter.class: Netgen\Bundle\ContentBrowserBundle\Adapter\EzTags\Adapter

    netgen_content_browser.tree.class: Netgen\Bundle\ContentBrowserBundle\Tree\Tree

    netgen_content_browser.event_listener.exception_conversion.class: Netgen\Bundle\ContentBrowserBundle\EventListener\ExceptionConversionListener

services:
    # API controllers

    netgen_content_browser.controller.api.tree:
        class: %netgen_content_browser.controller.api.tree.class%
        calls:
            - [setContainer, ["@service_container"]]

    # eZ Publish adapter

    netgen_content_browser.ezpublish.thumbnail_loader:
        alias: netgen_content_browser.ezpublish.thumbnail_loader.variation

    netgen_content_browser.ezpublish.thumbnail_loader.variation:
        class: %netgen_content_browser.ezpublish.thumbnail_loader.variation.class%
        arguments:
            - "@ezpublish.translation_helper"
            - "@ezpublish.field_helper"
            - "@ezpublish.fieldtype.ezimage.variation_service"
            - "%netgen_content_browser.adapters.ezpublish.image_fields%"
            - "%netgen_content_browser.adapters.ezpublish.variation_name%"

    netgen_content_browser.ezpublish.item_builder:
        class: %netgen_content_browser.ezpublish.item_builder.class%
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
            - "@netgen_content_browser.ezpublish.thumbnail_loader"

    netgen_content_browser.ezpublish.adapter:
        class: %netgen_content_browser.ezpublish.adapter.class%
        arguments:
            - "@ezpublish.api.service.search"
            - "@netgen_content_browser.ezpublish.item_builder"
        tags:
            - { name: netgen_content_browser.adapter, identifier: ezpublish }

    # eZ Tags adapter

    netgen_content_browser.eztags.item_builder:
        class: %netgen_content_browser.eztags.item_builder.class%
        arguments:
            - "@ezpublish.translation_helper"

    netgen_content_browser.eztags.adapter:
        class: %netgen_content_browser.eztags.adapter.class%
        arguments:
            - "@ezpublish.api.service.tags"
            - "@netgen_content_browser.eztags.item_builder"
        tags:
            - { name: netgen_content_browser.adapter, identifier: eztags }

    # Event listeners

    netgen_content_browser.event_listener.exception_conversion:
        class: %netgen_content_browser.event_listener.exception_conversion.class%
        tags:
            - { name: kernel.event_subscriber }
