parameters:
    netgen_content_browser.config.class: Netgen\Bundle\ContentBrowserBundle\Config\Configuration
    netgen_content_browser.config_loader.class: Netgen\Bundle\ContentBrowserBundle\Config\ConfigLoader

    netgen_content_browser.controller.base.class: Netgen\Bundle\ContentBrowserBundle\Controller\API\Controller
    netgen_content_browser.controller.api.config.class: Netgen\Bundle\ContentBrowserBundle\Controller\API\ConfigController
    netgen_content_browser.controller.api.browse.class: Netgen\Bundle\ContentBrowserBundle\Controller\API\BrowseController
    netgen_content_browser.controller.api.search.class: Netgen\Bundle\ContentBrowserBundle\Controller\API\SearchController
    netgen_content_browser.controller.api.items.class: Netgen\Bundle\ContentBrowserBundle\Controller\API\ItemsController

    netgen_content_browser.event_listener.set_is_api_request.class: Netgen\Bundle\ContentBrowserBundle\EventListener\SetIsApiRequestListener
    netgen_content_browser.event_listener.set_current_config.class: Netgen\Bundle\ContentBrowserBundle\EventListener\SetCurrentConfigListener
    netgen_content_browser.event_listener.exception_conversion.class: Netgen\Bundle\ContentBrowserBundle\EventListener\ExceptionConversionListener
    netgen_content_browser.event_listener.exception_serializer.class: Netgen\Bundle\ContentBrowserBundle\EventListener\ExceptionSerializerListener

    netgen_content_browser.registry.backend.class: Netgen\Bundle\ContentBrowserBundle\Registry\BackendRegistry

    netgen_content_browser.item_repository.class: Netgen\Bundle\ContentBrowserBundle\Item\ItemRepository
    netgen_content_browser.item_serializer.class: Netgen\Bundle\ContentBrowserBundle\Item\Serializer\ItemSerializer

    netgen_content_browser.item_renderer.class: Netgen\Bundle\ContentBrowserBundle\Item\Renderer\ItemRenderer
    netgen_content_browser.column_provider.class: Netgen\Bundle\ContentBrowserBundle\Item\ColumnProvider\ColumnProvider

    netgen_content_browser.form.type.content_browser.class: Netgen\Bundle\ContentBrowserBundle\Form\Type\ContentBrowserType
    netgen_content_browser.form.type.content_browser_dynamic.class: Netgen\Bundle\ContentBrowserBundle\Form\Type\ContentBrowserDynamicType
    netgen_content_browser.form.type.content_browser_multiple.class: Netgen\Bundle\ContentBrowserBundle\Form\Type\ContentBrowserMultipleType

    netgen_content_browser.param_converter.location.class: Netgen\Bundle\ContentBrowserBundle\ParamConverter\LocationParamConverter

    netgen_content_browser.column_value_provider.name.class: Netgen\Bundle\ContentBrowserBundle\Item\ColumnProvider\ColumnValueProvider\Name

services:
    # Config services

    netgen_content_browser.config:
        class: "%netgen_content_browser.config.class%"
        abstract: true
        arguments: [null, null]

    netgen_content_browser.current_config:
        synthetic: true

    netgen_content_browser.config_loader:
        class: "%netgen_content_browser.config_loader.class%"
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
            - []

    # API controllers

    netgen_content_browser.controller.base:
        class: "%netgen_content_browser.controller.base.class%"
        arguments:
            - "@netgen_content_browser.item_repository"
            - "@netgen_content_browser.item_serializer"
            - "@netgen_content_browser.current_config"
        calls:
            - [setContainer, ["@service_container"]]

    netgen_content_browser.controller.api.config:
        class: "%netgen_content_browser.controller.api.config.class%"
        parent: netgen_content_browser.controller.base

    netgen_content_browser.controller.api.browse:
        class: "%netgen_content_browser.controller.api.browse.class%"
        parent: netgen_content_browser.controller.base

    netgen_content_browser.controller.api.search:
        class: "%netgen_content_browser.controller.api.search.class%"
        parent: netgen_content_browser.controller.base

    netgen_content_browser.controller.api.items:
        class: "%netgen_content_browser.controller.api.items.class%"
        parent: netgen_content_browser.controller.base

    # Event listeners

    netgen_content_browser.event_listener.set_is_api_request:
        class: "%netgen_content_browser.event_listener.set_is_api_request.class%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.set_current_config:
        class: "%netgen_content_browser.event_listener.set_current_config.class%"
        arguments:
            - "@netgen_content_browser.config_loader"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.exception_conversion:
        class: "%netgen_content_browser.event_listener.exception_conversion.class%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.exception_serializer:
        class: "%netgen_content_browser.event_listener.exception_serializer.class%"
        calls:
            - [setOutputDebugInfo, ["%kernel.debug%"]]
        tags:
            - { name: kernel.event_subscriber }

    # Registries

    netgen_content_browser.registry.backend:
        class: "%netgen_content_browser.registry.backend.class%"

    # Main services

    netgen_content_browser.item_repository:
        class: "%netgen_content_browser.item_repository.class%"
        arguments:
            - "@netgen_content_browser.registry.backend"

    netgen_content_browser.item_serializer:
        class: "%netgen_content_browser.item_serializer.class%"
        arguments:
            - "@netgen_content_browser.item_repository"
            - "@netgen_content_browser.column_provider"
            - "@netgen_content_browser.item_renderer"
            - "@netgen_content_browser.current_config"
            - []

    netgen_content_browser.item_renderer:
        class: "%netgen_content_browser.item_renderer.class%"
        arguments:
            - "@twig"
            - []

    netgen_content_browser.column_provider:
        class: "%netgen_content_browser.column_provider.class%"
        arguments:
            - "@netgen_content_browser.item_renderer"
            - "@netgen_content_browser.current_config"
            - []

    # Form types

    netgen_content_browser.form.type.content_browser:
        class: "%netgen_content_browser.form.type.content_browser.class%"
        arguments:
            - "@netgen_content_browser.item_repository"
        tags:
            - { name: form.type }

    netgen_content_browser.form.type.content_browser_dynamic:
        class: "%netgen_content_browser.form.type.content_browser_dynamic.class%"
        arguments:
            - "@netgen_content_browser.item_repository"
            - "%netgen_content_browser.item_types%"
        tags:
            - { name: form.type }

    netgen_content_browser.form.type.content_browser_multiple:
        class: "%netgen_content_browser.form.type.content_browser_multiple.class%"
        arguments:
            - "@netgen_content_browser.item_repository"
        tags:
            - { name: form.type }

    # Param converters

    netgen_content_browser.param_converter.location:
        class: "%netgen_content_browser.param_converter.location.class%"
        arguments:
            - "@netgen_content_browser.item_repository"
        tags:
            - { name: request.param_converter, priority: 0 }

    # Column value providers

    netgen_content_browser.column_value_provider.name:
        class: "%netgen_content_browser.column_value_provider.name.class%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: name }
