dist: bionic

language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.cache/composer

env:
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0"
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~4.4.0"
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~5.0.0"
  - PHPUNIT_CONFIG="phpunit-api.xml" SYMFONY_VERSION="~3.4.0"
  - PHPUNIT_CONFIG="phpunit-api.xml" SYMFONY_VERSION="~4.4.0"
  - PHPUNIT_CONFIG="phpunit-api.xml" SYMFONY_VERSION="~5.0.0"

matrix:
  include:
    - php: 7.2
      env: PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0" DEPS="low"
    - php: 7.2
      env: PHPUNIT_CONFIG="phpunit-api.xml" SYMFONY_VERSION="~3.4.0" DEPS="low"
    - php: 7.4
      env: RUN_PHPSTAN="yes"
    - php: 7.4
      env: RUN_PSALM="yes"
  fast_finish: true

branches:
  only:
    - master
    - /^\d.\d+$/

before_script:
  - phpenv config-rm xdebug.ini || true
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  # Install Flex as a global dependency to enable usage of extra.symfony.require
  # while keeping Flex recipes from applying
  - composer global require --no-scripts symfony/flex

  - if [ "$SYMFONY_VERSION" != "" ] ; then composer config extra.symfony.require $SYMFONY_VERSION ; fi

  - |
    if [ "$DEPS" = "low" ] ; then
      composer update --no-suggest --prefer-dist --prefer-lowest --prefer-stable
    else
      composer update --no-suggest --prefer-dist
    fi

script:
  - composer validate --strict
  - if [ "$PHPUNIT_CONFIG" != "" ] ; then vendor/bin/phpunit -c $PHPUNIT_CONFIG --colors=always ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan-tests ; fi
  - if [ "$RUN_PSALM" != "" ] ; then composer psalm ; fi

notifications:
  email: false
  slack:
    rooms:
      - secure: "GqfXIXTQrkgeR18N5KnOYwkHKNzqiZ9DOkYzxEpMtE0CqzttSvoAbnFXcZa7yv0Utk9PxyzQP4aD52TTT1yLoHtjaxSskkLbmmvqsm3lYPjSnOAVp3EESXc8vgDyXHaxiJulXp3Tfsrs3dMzFNc215ULU1NxLhBVoXXc3f3FpQBS2zzxXPZ8D/Za+9OkOLJdRIPSVl4ZchAmU6wNObmL+EISXV+xiOAtCeEUUAtt9YhKz1U8HOdvvej0sPyHAccFmUA2gRFGDuJ0SQnvYkHKq3yWQOKchM1ewRw/cPZHRDz2mX3lUlLU9lfjXXG38OoVT+G5E0Geq8xEcqAT795Q8H7CXRwfNKQI9jv+Dq5D9dURETyOvbSjbGVnv1AhBvsPRPgdbPYpf4FYXg2ltc5brsni0Vlb7axJrYtsPRBTNBVEklM2loHP2FUg2JTBWKCC2a0pnZHGiGR58fDYK8mfhuh3aaCK5vMzsp8reoaBMsNEaI2C0V85UjPEZIoRinjStspLkbwZikE5TSEwPIpDXITmQZ9wZtyl56K9aeNCuTtYXQJs6PE0RyCD451cHrieYJzxvgkrBI9Wa8tBjBQhiIe271zrr5RnEEQUWPvlusv5rCcfvBnaczDYU54D8wND3sL5XyEYCOwkzm4R/q+ha6PTzYMvlbD8j0qv0IaKUYg="
    on_success: change
    on_failure: always
    on_pull_requests: always

git:
  depth: 1
