ngcb_api_v1_config:
    path: /{itemType}/config
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.config:getConfig"

ngcb_api_v1_browse_locations:
    path: /{itemType}/browse/{locationId}/locations
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.browse:getSubLocations"

ngcb_api_v1_browse_items:
    path: /{itemType}/browse/{locationId}/items
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.browse:getSubItems"

ngcb_api_v1_item_render:
    path: /{itemType}/render/{itemId}
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.item:renderItem"

ngcb_api_v1_item_values:
    path: /{itemType}/values
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.item:getByValues"

ngcb_api_v1_search:
    path: /{itemType}/search
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.search:search"
