services:
    # Config services

    netgen_content_browser.current_config:
        synthetic: true
        public: true

    # API controllers

    netgen_content_browser.controller.base:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\Controller
        public: false
        abstract: true
        arguments:
            - "@netgen_content_browser.current_backend"
            - "@netgen_content_browser.current_config"
            - "@netgen_content_browser.item_serializer"
        calls:
            - [initialize, ["@service_container"]]

    netgen_content_browser.controller.api.config:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\ConfigController
        parent: netgen_content_browser.controller.base
        public: true

    netgen_content_browser.controller.api.browse:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\BrowseController
        parent: netgen_content_browser.controller.base
        public: true

    netgen_content_browser.controller.api.search:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\SearchController
        parent: netgen_content_browser.controller.base
        public: true

    netgen_content_browser.controller.api.items:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\ItemsController
        parent: netgen_content_browser.controller.base
        public: true

    # Event listeners

    netgen_content_browser.event_listener.set_is_api_request:
        class: Netgen\Bundle\ContentBrowserBundle\EventListener\SetIsApiRequestListener
        # public: false
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.set_current_config:
        class: Netgen\Bundle\ContentBrowserBundle\EventListener\SetCurrentConfigListener
        # public: false
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.set_current_backend:
        class: Netgen\Bundle\ContentBrowserBundle\EventListener\SetCurrentBackendListener
        # public: false
        arguments:
            - "@service_container"
            - "@netgen_content_browser.registry.backend"
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.exception_conversion:
        class: Netgen\Bundle\ContentBrowserBundle\EventListener\ExceptionConversionListener
        # public: false
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.exception_serializer:
        class: Netgen\Bundle\ContentBrowserBundle\EventListener\ExceptionSerializerListener
        # public: false
        arguments:
            - "@?logger"
        calls:
            - [setOutputDebugInfo, ["%kernel.debug%"]]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: ngcb }

    # Registries

    netgen_content_browser.registry.backend:
        class: Netgen\ContentBrowser\Registry\BackendRegistry
        public: true

    # Main services

    netgen_content_browser.current_backend:
        synthetic: true
        public: true

    netgen_content_browser.item_serializer:
        class: Netgen\ContentBrowser\Item\Serializer\ItemSerializer
        public: false
        arguments:
            - "@netgen_content_browser.current_backend"
            - "@netgen_content_browser.current_config"
            - "@netgen_content_browser.column_provider"
            - "@netgen_content_browser.item_renderer"

    netgen_content_browser.item_renderer:
        class: Netgen\ContentBrowser\Item\Renderer\ItemRenderer
        public: false
        arguments:
            - "@twig"
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: ngcb }

    netgen_content_browser.column_provider:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnProvider
        public: false
        arguments:
            - "@netgen_content_browser.item_renderer"
            - "@netgen_content_browser.current_config"
            - []

    # Form types

    netgen_content_browser.form.type.content_browser:
        class: Netgen\ContentBrowser\Form\Type\ContentBrowserType
        # public: false
        arguments:
            - "@netgen_content_browser.registry.backend"
        tags:
            - { name: form.type }

    netgen_content_browser.form.type.content_browser_dynamic:
        class: Netgen\ContentBrowser\Form\Type\ContentBrowserDynamicType
        # public: false
        arguments:
            - "@netgen_content_browser.registry.backend"
            - "%netgen_content_browser.item_types%"
        tags:
            - { name: form.type }

    netgen_content_browser.form.type.content_browser_multiple:
        class: Netgen\ContentBrowser\Form\Type\ContentBrowserMultipleType
        # public: false
        arguments:
            - "@netgen_content_browser.registry.backend"
        tags:
            - { name: form.type }

    # Param converters

    netgen_content_browser.param_converter.location:
        class: Netgen\Bundle\ContentBrowserBundle\ParamConverter\LocationParamConverter
        public: false
        arguments:
            - "@netgen_content_browser.registry.backend"
        tags:
            - { name: request.param_converter, priority: 0 }

    # Column value providers

    netgen_content_browser.column_value_provider.name:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\Name
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: name }
