services:
    # Config services

    netgen_content_browser.current_config:
        synthetic: true
        public: true

    # API controllers

    netgen_content_browser.controller.base:
        class: Symfony\Bundle\FrameworkBundle\Controller\AbstractController
        public: false
        abstract: true
        calls:
            - [setContainer, ["@service_container"]]

    netgen_content_browser.controller.api.load_config:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\LoadConfig
        parent: netgen_content_browser.controller.base
        public: true
        arguments:
            - "@netgen_content_browser.current_backend"
            - "@netgen_content_browser.current_config"
            - "@netgen_content_browser.item_serializer"
            - "@translator"

    netgen_content_browser.controller.api.load_sub_locations:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\LoadSubLocations
        parent: netgen_content_browser.controller.base
        public: true
        arguments:
            - "@netgen_content_browser.current_backend"
            - "@netgen_content_browser.item_serializer"

    netgen_content_browser.controller.api.load_sub_items:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\LoadSubItems
        parent: netgen_content_browser.controller.base
        public: true
        arguments:
            - "@netgen_content_browser.current_backend"
            - "@netgen_content_browser.item_serializer"
            - "@netgen_content_browser.pager.factory"
            - "%netgen_content_browser.browser.default_limit%"

    netgen_content_browser.controller.api.search_items:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\SearchItems
        parent: netgen_content_browser.controller.base
        public: true
        arguments:
            - "@netgen_content_browser.current_backend"
            - "@netgen_content_browser.item_serializer"
            - "@netgen_content_browser.pager.factory"
            - "%netgen_content_browser.browser.default_limit%"

    netgen_content_browser.controller.api.render_item:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\RenderItem
        parent: netgen_content_browser.controller.base
        public: true
        arguments:
            - "@netgen_content_browser.current_config"
            - "@netgen_content_browser.item_renderer"

    netgen_content_browser.controller.api.load_items_by_value:
        class: Netgen\Bundle\ContentBrowserBundle\Controller\API\LoadItemsByValue
        parent: netgen_content_browser.controller.base
        public: true
        arguments:
            - "@netgen_content_browser.current_backend"
            - "@netgen_content_browser.item_serializer"

    # Event listeners

    netgen_content_browser.event_listener.set_is_api_request:
        class: Netgen\Bundle\ContentBrowserBundle\EventListener\SetIsApiRequestListener
        # public: false
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.set_current_config:
        class: Netgen\Bundle\ContentBrowserBundle\EventListener\SetCurrentConfigListener
        # public: false
        arguments:
            - "@service_container"
            - "@event_dispatcher"
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.set_current_backend:
        class: Netgen\Bundle\ContentBrowserBundle\EventListener\SetCurrentBackendListener
        # public: false
        arguments:
            - "@service_container"
            - "@netgen_content_browser.registry.backend"
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.exception_conversion:
        class: Netgen\Bundle\ContentBrowserBundle\EventListener\ExceptionConversionListener
        # public: false
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.exception_serializer:
        class: Netgen\Bundle\ContentBrowserBundle\EventListener\ExceptionSerializerListener
        # public: false
        arguments:
            - "%kernel.debug%"
            - "@?logger"
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: ngcb }

    # Registries

    netgen_content_browser.registry.backend:
        class: Netgen\ContentBrowser\Registry\BackendRegistry
        public: true
        arguments:
            - []

    netgen_content_browser.registry.config:
        class: Netgen\ContentBrowser\Registry\ConfigRegistry
        public: true
        arguments:
            - []

    # Main services

    netgen_content_browser.current_backend:
        synthetic: true
        public: true

    netgen_content_browser.item_serializer:
        class: Netgen\ContentBrowser\Item\Serializer\ItemSerializer
        public: false
        arguments:
            - "@netgen_content_browser.current_backend"
            - "@netgen_content_browser.column_provider"

    netgen_content_browser.item_renderer:
        class: Netgen\ContentBrowser\Item\Renderer\ItemRenderer
        public: false
        arguments:
            - "@twig"
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: ngcb }

    netgen_content_browser.column_provider:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnProvider
        public: false
        arguments:
            - "@netgen_content_browser.item_renderer"
            - "@netgen_content_browser.current_config"
            - []

    # Form types

    netgen_content_browser.form.type.content_browser:
        class: Netgen\ContentBrowser\Form\Type\ContentBrowserType
        # public: false
        arguments:
            - "@netgen_content_browser.registry.backend"
        tags:
            - { name: form.type }

    netgen_content_browser.form.type.content_browser_dynamic:
        class: Netgen\ContentBrowser\Form\Type\ContentBrowserDynamicType
        # public: false
        arguments:
            - "@netgen_content_browser.registry.backend"
            - "@netgen_content_browser.registry.config"
        tags:
            - { name: form.type }

    netgen_content_browser.form.type.content_browser_multiple:
        class: Netgen\ContentBrowser\Form\Type\ContentBrowserMultipleType
        # public: false
        arguments:
            - "@netgen_content_browser.registry.backend"
        tags:
            - { name: form.type }

    # Param converters

    netgen_content_browser.param_converter.item:
        class: Netgen\Bundle\ContentBrowserBundle\ParamConverter\ItemParamConverter
        public: false
        arguments:
            - "@netgen_content_browser.registry.backend"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_content_browser.param_converter.location:
        class: Netgen\Bundle\ContentBrowserBundle\ParamConverter\LocationParamConverter
        public: false
        arguments:
            - "@netgen_content_browser.registry.backend"
        tags:
            - { name: request.param_converter, priority: 0 }

    # Column value providers

    netgen_content_browser.column_value_provider.name:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\Name
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: name }

    # Pager

    netgen_content_browser.pager.factory:
        class: Netgen\ContentBrowser\Pager\PagerFactory
        public: false
        arguments:
            - "%netgen_content_browser.browser.max_limit%"
