netgen_content_browser_api_v1_config:
    path: /{config}/config
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.config:getConfig"

netgen_content_browser_api_v1_values:
    path: /{config}/values
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.browse:getValues"

netgen_content_browser_api_v1_browse_children:
    path: /{config}/browse/{valueId}/children
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.browse:getChildren"

netgen_content_browser_api_v1_browse_categories:
    path: /{config}/browse/{valueId}/categories
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.browse:getSubCategories"

netgen_content_browser_api_v1_search:
    path: /{config}/search
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.search:search"
