netgen_content_browser_api_v1_config:
    path: /{config}/config
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.config:getConfig"

netgen_content_browser_api_v1_values:
    path: /{config}/values
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.items:getValues"

netgen_content_browser_api_v1_browse_children:
    path: /{config}/browse/{categoryId}/children
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.items:getSubItems"

netgen_content_browser_api_v1_browse_categories:
    path: /{config}/browse/{categoryId}/categories
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.categories:getSubCategories"

netgen_content_browser_api_v1_search:
    path: /{config}/search
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.search:search"
