netgen_content_browser_api_v1_config:
    path: /{config}/config
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.config:getConfig"

netgen_content_browser_api_v1_browse_locations:
    path: /{config}/browse/{locationId}/categories
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.browse:getSubLocations"

netgen_content_browser_api_v1_browse_items:
    path: /{config}/browse/{locationId}/children
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.browse:getSubItems"

netgen_content_browser_api_v1_items_values:
    path: /{config}/values
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.items:getByValues"

netgen_content_browser_api_v1_search:
    path: /{config}/search
    methods: [GET]
    defaults:
        _controller: "netgen_content_browser.controller.api.search:search"
